[package]
name = "wd"
version = "0.1.0"
authors = ["Sotaro Tommykawa <tommysouta@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "wd - a command line tool for print specified position of words"


[dependencies]
structopt = "0.3"
